'\" t
.\"     Title: dbench
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 10/20/2013
.\"    Manual: dbench: a multiprotocol loadtester.
.\"    Source: dbench
.\"  Language: English
.\"
.TH "DBENCH" "1" "10/20/2013" "dbench" "dbench: a multiprotocol loadte"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dbench \- Utility to perform loadtesting for multiple protocols\&.
.SH "SYNOPSIS"
.HP \w'\fBdbench\ [\ OPTIONS\ ]\ <num\-clients>\fR\ 'u
\fBdbench [ OPTIONS ] <num\-clients>\fR
.HP \w'\fBdbench\fR\ 'u
\fBdbench\fR [\-B\ \-\-backend=<backend>] [\-t\ \-\-timelimit=<seconds>] [\-\-warmup=<seconds>] [\-c\ \-\-loadfile=<filename>] [\-R\ \-\-targe\-trate=<throughput>] [\-\-trunc\-io=<size>] [\-\-run\-once] [\-\-machine\-readable] [\-\-iscsi=<iSCSI\ url>] [\-\-iscsi\-initiatorname=<iqn\ name>] [\-\-nfs=<nfs\ url>] [\-\-smb\-share=<//SERVER/SHARE>] [\-\-smb\-user=<user%password>] [\-\-scsi=<device>] [\-\-allow\-scsi\-writes]
.SH "DESCRIPTION"
.PP
Dbench is a utility to loadtest network server\&. Dbench currently supports iSCSI, NFSv3, SCSI and SMB\&.
.SH "OPTIONS"
.PP
\-B \-\-backend=<iscsi|nfs|scsi|smb>
.RS 4
This specifies which protocol to test with\&. Supported protocols are iscsi, nfsv3, scsi and smbv1
.RE
.PP
\-t \-\-timelimit=<seconds>
.RS 4
For how long to run the test\&. This argument is mutually exclusive with \-\-run\-once\&.
.RE
.PP
\-\-warmup=<seconds>
.RS 4
Before starting to record throughput and latencies dbench will first wait until all clients are running and then wait for the target and its caches to warm up before it starts collecting data\&.
.sp
Setting warmup to 0 means not warmup and dbench will start running the test immediately\&.
.RE
.PP
\-c \-\-loadfile=<filename>
.RS 4
The loadfile is the script for the commands to run during the test\&. This command is mandatory\&.
.sp
The loadfile is the script for the commands to run during the test\&. This command is mandatory\&. The content of this file depends on the backend protocol that is beeing tested\&. See the protocol specific sections below for the commands that apply to the backends\&.
.RE
.PP
\-R \-\-targetrate=<throughput>
.RS 4
If the target rate is used dbench will try to keep each client running at the indicated throughput rate by adjusting a delta that the dbench thread will sleep between commands\&.
.sp
This is mainly useful for capacity testing of a known workload\&. By using this argument it is possible to run each thread to match the timings for the specific workload\&. By increasing the number of threads until the target can no longer keep up it is possible to measure how many clents/threads the target can service before it becomes saturated and it can no longer keep up\&.
.RE
.PP
\-\-trunc\-io=<integer>
.RS 4
Some targets may have limits on the size of I/O they can accept\&. This argument will clamp all I/O read from the loadfile to not exceed this value\&. This is mainly useful for using generic loadfiles against targets that can not handle the I/O size\&.
.RE
.PP
\-\-run\-once
.RS 4
Run the workload exactly once for each thread and exit the test once all threads have finished\&. This option is mutualy exclusive with \-\-timelimit\&.
.RE
.PP
\-\-machine\-readable
.RS 4
Output data during in a more machine friendly format\&.
.RE
.PP
\-\-iscsi=<iSCSI url>
.RS 4
iSCSI url for the target to connect to\&. The url format is : iscsi://[<username>[%<password>]@]<host>[:<port>]/<target\-iqn>/<lun>
.sp
Username and password are only required if the target requires CHAP authentication\&. Optionally you can specify the username and password using the environment variables LIBISCSI_CHAP_USERNAME and LIBISCSI_CHAP_PASSWORD\&.
.sp
Host can be specified either as a hostname, an IPv4 address or an IPv6 address\&. Examples:
.sp
.if n \{\
.RS 4
.\}
.nf
	      iscsi://192\&.0\&.2\&.1/iqn\&.ronnie\&.test/1
	      iscsi://[2001:DB8::1]:3261/iqn\&.ronnie\&.test/1
	      iscsi://ronnie%password@iscsi\&.example\&.com/iqn\&.ronnie\&.test/1
	    
.fi
.if n \{\
.RE
.\}
.sp
This argument is only valid with iSCSI backend\&.
.RE
.PP
\-\-iscsi\-initiatorname=<iqn name>
.RS 4
iSCSI initatorname to use when connecting to the target\&.
.sp
This argument is only valid with iSCSI backend\&.
.RE
.PP
\-\-nfs=<NFS url>
.RS 4
NFS url for the target to connect to\&. The url format is : nfs://<server>/<path\-of\-export>
.sp
This argument is only valid with NFS backend\&.
.RE
.PP
\-\-scsi=<SCSI device>
.RS 4
Device name for the device to test\&.
.sp
This argument is only valid with SCSI backend\&.
.RE
.PP
\-\-allow\-scsi\-write
.RS 4
Allow sending medium write commands to the device\&.
.sp
This argument is only valid with SCSI backend\&.
.RE
.PP
\-\-smb\-share=<//SERVER/SHARE>
.RS 4
Server and share to connect to for the SMB backend\&.
.sp
This argument is only valid with SMB backend\&.
.RE
.PP
\-\-smb\-user=<user%password>
.RS 4
Username and password to authenticate to the SMB server with\&.
.sp
This argument is only valid with SMB backend\&.
.RE
.SH "SEE ALSO"
.PP
dbench(1)
\m[blue]\fB\%http://github.com/sahlberg/dbench\fR\m[]
